#!/usr/bin/env python3
"""test-xml-gen-e2e.py -- Linux-side end-to-end test for the answer-file generator.

tools/Test-UnattendXml.ps1 is the full validation suite but needs PowerShell,
which this Linux VM does not have. This is the portable end-to-end: it
re-implements New-UnattendXml.ps1's exact substitution rules (validated
against the PS suite's proven hash vectors), generates a real
autounattend.xml into a temp dir in /tmp (NEVER the repo -- the filled file
carries passwords and win-install/staging/ is gitignored), and asserts the
output is well-formed, token-free, credential-correct, and round-trippable
through the Schneegans comment URL.

Usage: python3 tests/tools/test-xml-gen-e2e.py   (exit 0 = all green)
"""
import base64
import re
import sys
import tempfile
import urllib.parse
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TEMPLATE = REPO / "win-install" / "autounattend.template.xml"

PASS = 0
FAIL = 0
FAILED = []


def ok(name):
    global PASS
    PASS += 1
    print(f"  PASS: {name}")


def bad(name, why=""):
    global FAIL
    FAIL += 1
    FAILED.append(name)
    print(f"  FAIL: {name}{' -- ' + why if why else ''}")


# --- replicas of the PS generator's rules -------------------------------------
def obscure(pw):  # Schneegans: base64( UTF-16LE( password + "Password" ) )
    return base64.b64encode((pw + "Password").encode("utf-16-le")).decode()


def urlenc(v):  # [Uri]::EscapeDataString, spaces as '+'
    return urllib.parse.quote(v, safe="-._~").replace("%20", "+")


def xmlesc(v):  # [SecurityElement]::Escape
    return (v.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;").replace("'", "&apos;"))


def validate(computer, user, std_user, product_key):
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9\-]{0,14}", computer):
        raise ValueError(f"bad ComputerName: {computer!r}")
    if not user:
        raise ValueError("Username empty")
    if std_user and std_user == user:
        raise ValueError("StandardUsername must differ from Username")
    if not re.fullmatch(r"[A-Z0-9]{5}(-[A-Z0-9]{5}){4}", product_key, re.I):
        raise ValueError(f"bad ProductKey: {product_key!r}")


def generate(computer="TEST-PC", user="testadmin", pw="S3cret!Test",
             std_user="testuser", std_pw="G2pass!Test",
             tz="Central Standard Time", edition="Windows 11 Pro",
             key="VK7JG-NPHTM-C97JM-9MPGT-3V66T", out=None):
    validate(computer, user, std_user, key)
    content = TEMPLATE.read_text(encoding="utf-8")

    # -- rewrite the Schneegans generator comment --
    m = re.search(r"<!--https://schneegans\.de/windows/unattend-generator/\?.*?-->",
                  content, re.S)
    if not m:
        raise ValueError("template missing Schneegans comment")
    comment = m.group(0)
    for tok, val in (("COMPUTER_NAME", computer), ("TIME_ZONE", tz),
                     ("EDITION_NAME", edition), ("PRODUCT_KEY", key),
                     ("ACCOUNT_NAME", user), ("ACCOUNT_PASSWORD", pw)):
        comment = comment.replace("{{" + tok + "}}", urlenc(val))
    if std_user:
        comment = comment.replace("{{STANDARD_ACCOUNT_NAME}}", urlenc(std_user))
        comment = comment.replace("{{STANDARD_ACCOUNT_PASSWORD}}", urlenc(std_pw))
    else:
        comment = re.sub(r"&Account(Name|DisplayName|Password|Group)1=[^&]*", "", comment)
    content = content[:m.start()] + comment + content[m.end():]
    stamp = ("<!-- Generated by Phoenix answer-file generator (python e2e port). "
             "CONTAINS REAL CREDENTIALS, DO NOT COMMIT. -->")
    content = content.replace(comment, comment + "\n\t" + stamp)

    # -- fill body tokens --
    admin_b64 = obscure(pw)
    if std_user:
        std_b64 = obscure(std_pw)
        std_name = xmlesc(std_user)
        block = ('<LocalAccount wcm:action="add">\n'
                 '\t\t\t\t\t\t<Name>' + std_name + '</Name>\n'
                 '\t\t\t\t\t\t<DisplayName></DisplayName>\n'
                 '\t\t\t\t\t\t<Group>Users</Group>\n'
                 '\t\t\t\t\t\t<Password>\n'
                 '\t\t\t\t\t\t\t<Value>' + std_b64 + '</Value>\n'
                 '\t\t\t\t\t\t\t<PlainText>false</PlainText>\n'
                 '\t\t\t\t\t\t</Password>\n'
                 '\t\t\t\t\t</LocalAccount>')
        content = content.replace("{{STANDARD_ACCOUNT_XML}}", block)
    else:
        content = re.sub(r"(?m)^\t*{{STANDARD_ACCOUNT_XML}}\r?\n", "", content)
    content = content.replace("{{COMPUTER_NAME}}", xmlesc(computer))
    content = content.replace("{{PRODUCT_KEY}}", key)
    content = content.replace("{{TIME_ZONE}}", xmlesc(tz))
    content = content.replace("{{EDITION_NAME}}", edition)
    content = content.replace("{{ACCOUNT_NAME}}", xmlesc(user))
    content = content.replace("{{ACCOUNT_PASSWORD_B64}}", admin_b64)

    leftover = re.search(r"\{\{[A-Z_]+\}\}", content)
    if leftover:
        raise ValueError(f"unfilled token: {leftover.group(0)}")
    ET.fromstring(content)  # well-formedness gate
    Path(out).write_text(content.replace("\r\n", "\n"), encoding="utf-8")
    return Path(out)


# --- tests ---------------------------------------------------------------------
print("== answer-file generator end-to-end (python port) ==")

# E1: PS proven hash vectors -- the port must reproduce Schneegans exactly.
if obscure("123456789abcdefghi") == \
        "MQAyADMANAA1ADYANwA4ADkAYQBiAGMAZABlAGYAZwBoAGkAUABhAHMAcwB3AG8AcgBkAA==":
    ok("obfuscation matches proven admin hash (PS test vector)")
else:
    bad("obfuscation matches proven admin hash", obscure("123456789abcdefghi"))
if obscure("abcdefghi123456789") == \
        "YQBiAGMAZABlAGYAZwBoAGkAMQAyADMANAA1ADYANwA4ADkAUABhAHMAcwB3AG8AcgBkAA==":
    ok("obfuscation matches proven standard-user hash (PS test vector)")
else:
    bad("obfuscation matches proven standard-user hash")

with tempfile.TemporaryDirectory(prefix="phoenix-unattend-e2e-") as tmp:
    tmp = Path(tmp)

    # E2: two-account generation into /tmp.
    out = generate(out=tmp / "autounattend.xml")
    ok("two-account generation completes without error")

    # E3: well-formed XML.
    try:
        ET.parse(out)
        ok("generated file is well-formed XML")
    except ET.ParseError as e:
        bad("generated file is well-formed XML", str(e))

    raw = out.read_text(encoding="utf-8")

    # E4: token-free.
    bad_tokens = re.findall(r"\{\{[A-Za-z0-9_]+\}\}", raw)
    if not bad_tokens:
        ok("generated file is token-free")
    else:
        bad("generated file is token-free", str(bad_tokens[:3]))

    # E5: all 7 passes present.
    passes = re.findall(r'<settings pass="([^"]+)"', raw)
    expected = {"offlineServicing", "windowsPE", "generalize", "specialize",
                "auditSystem", "auditUser", "oobeSystem"}
    if set(passes) == expected:
        ok("all 7 unattend passes present")
    else:
        bad("all 7 unattend passes present", f"got {sorted(set(passes))}")

    # E6: key components where the installer needs them.
    checks = [
        ("Microsoft-Windows-Setup in windowsPE", "Microsoft-Windows-Setup" in raw),
        ("UserAccounts in oobeSystem", "UserAccounts" in raw),
        ("both account names present", "testadmin" in raw and "testuser" in raw),
        ("AutoLogon for admin", "<AutoLogon>" in raw and
         raw.count("testadmin") >= 2),
        ("admin obfuscated password embedded", obscure("S3cret!Test") in raw),
        ("standard obfuscated password embedded", obscure("G2pass!Test") in raw),
        ("no plaintext passwords", "S3cret!Test" not in raw.split("<!--")[0] and
         "G2pass!Test" not in raw),
        ("generic Pro key default", "VK7JG-NPHTM-C97JM-9MPGT-3V66T" in raw),
        ("comment URL reflects ComputerName", "ComputerName=TEST-PC" in raw),
        ("comment URL keeps second account", "AccountName1=testuser" in raw),
        ("origin stamp present", "DO NOT COMMIT" in raw),
    ]
    for name, good in checks:
        ok(name) if good else bad(name)

    # E7: single-account variant drops Account1 params and the XML block.
    out1 = generate(std_user="", std_pw="", out=tmp / "solo.xml")
    raw1 = out1.read_text(encoding="utf-8")
    if "AccountName1=" not in raw1 and "LocalAccount" in raw1:
        ok("single-account file drops Account1 params, keeps admin block")
    else:
        bad("single-account file drops Account1 params",
            "Account1 params survived or admin block missing")
    if not re.search(r"\{\{[A-Z_]+\}\}", raw1):
        ok("single-account file is token-free")
    else:
        bad("single-account file is token-free")

    # E8: UTF-8, no BOM, LF endings (matches PS WriteAllText settings).
    data = out.read_bytes()
    if not data.startswith(b"\xef\xbb\xbf") and b"\r\n" not in data:
        ok("UTF-8 no-BOM, LF line endings")
    else:
        bad("UTF-8 no-BOM, LF line endings")

    # E9: failure modes mirror the PS generator's guards.
    def expect_fail(name, **kw):
        try:
            generate(out=tmp / "fail.xml", **kw)
            bad(name, "expected ValueError, generation succeeded")
        except ValueError:
            ok(name)

    expect_fail("rejects bad ComputerName", computer="not a valid name!")
    expect_fail("rejects duplicate account names", std_user="testadmin")
    expect_fail("rejects bad product key", key="NOT-A-KEY")
    expect_fail("rejects empty username", user="")

    # E10: output lands in /tmp only -- nothing written into the repo.
    staging = REPO / "win-install" / "staging"
    stray = list(staging.glob("*.xml")) if staging.is_dir() else []
    if not stray:
        ok("no generated file written into the repo tree")
    else:
        bad("no generated file written into the repo tree",
            f"{[p.name for p in stray]} in win-install/staging/")

print(f"PASS: {PASS}  FAIL: {FAIL}")
if FAILED:
    print("Failed cases:", " ".join(FAILED))
sys.exit(1 if FAIL else 0)
