#!/usr/bin/env bash
#===============================================================================
# test-xml-twin.sh -- regression suite for tools/New-UnattendXml.sh
#
# The bash twin must be a drop-in replacement for the PowerShell generator
# and for the python e2e port (tests/tools/test-xml-gen-e2e.py), which
# encodes the PS suite's proven hash vectors. All generated files go to a
# temp dir -- NEVER the repo (the filled files carry passwords).
#
# Usage: bash tests/tools/test-xml-twin.sh   (exit 0 = all green)
#===============================================================================
set -uo pipefail
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
TWIN="$REPO/tools/New-UnattendXml.sh"
PASS=0; FAIL=0
pass() { PASS=$((PASS+1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL+1)); echo "  FAIL: $1${2:+ -- $2}"; }

TMP="$(mktemp -d /tmp/phx-xml-twin.XXXXXX)"
trap 'rm -rf "$TMP"' EXIT

[[ -x "$TWIN" ]] || chmod +x "$TWIN"

# T1: twin runs; proven Schneegans hash vectors land in the XML.
OUT="$TMP/solo.xml"
"$TWIN" --computer-name TESTBOX --username brando --password '123456789abcdefghi' \
        --standard-username '' --output "$OUT" --force >/dev/null 2>&1 \
    && pass "twin generates single-account file" \
    || fail "twin generates single-account file"
grep -q 'MQAyADMANAA1ADYANwA4ADkAYQBiAGMAZABlAGYAZwBoAGkAUABhAHMAcwB3AG8AcgBkAA==' "$OUT" \
    && pass "obscured admin password matches proven PS hash vector" \
    || fail "obscured admin password matches proven PS hash vector"
python3 -c "import xml.dom.minidom,sys; xml.dom.minidom.parse(sys.argv[1])" "$OUT" 2>/dev/null \
    && pass "twin output is well-formed XML" \
    || fail "twin output is well-formed XML"
grep -q '{{[A-Za-z0-9_]*}}' "$OUT" \
    && fail "twin output is token-free" \
    || pass "twin output is token-free"
grep -q 'AccountName1=' "$OUT" \
    && fail "single-account file drops second-account regen params" \
    || pass "single-account file drops second-account regen params"
# LF endings, no BOM
if head -c3 "$OUT" | grep -q $'\xef\xbb\xbf'; then fail "UTF-8 no-BOM"; else pass "UTF-8 no-BOM"; fi
grep -qU $'\r' "$OUT" && fail "LF line endings" || pass "LF line endings"

# T2: two-account generation; standard hash vector matches.
OUT2="$TMP/duo.xml"
"$TWIN" --computer-name TESTBOX --username brando --password 'S3cret!Test' \
        --standard-username guest --standard-password 'abcdefghi123456789' \
        --output "$OUT2" --force >/dev/null 2>&1 \
    && pass "twin generates two-account file" \
    || fail "twin generates two-account file"
grep -q 'YQBiAGMAZABlAGYAZwBoAGkAMQAyADMANAA1ADYANwA4ADkAUABhAHMAcwB3AG8AcgBkAA==' "$OUT2" \
    && pass "obscured standard password matches proven PS hash vector" \
    || fail "obscured standard password matches proven PS hash vector"
grep -q '<Group>Users</Group>' "$OUT2" \
    && pass "standard account lands in Users group" \
    || fail "standard account lands in Users group"

# T3: byte-parity with the python e2e port (the PS-behavior reference).
# Load the port's definitions only (its test body runs at import).
REF="$TMP/ref.xml"
python3 - "$REPO/tests/tools/test-xml-gen-e2e.py" "$REF" <<'PYEOF'
import sys
src = open(sys.argv[1]).read()
src = src.split("# --- tests ---")[0]          # definitions only, no test body
ns = {"__name__": "phx_ref", "__file__": sys.argv[1]}
exec(compile(src, sys.argv[1], "exec"), ns)
ns["generate"](computer="PARITY-PC", user="parityadmin", pw="P4rity!Pw",
               std_user="parityuser", std_pw="U5er!Pw",
               tz="Central Standard Time", edition="Windows 11 Pro",
               key="VK7JG-NPHTM-C97JM-9MPGT-3V66T", out=sys.argv[2])
PYEOF
[[ -f "$REF" ]] || fail "reference port generation ran"
SH="$TMP/ref-twin.xml"
"$TWIN" --computer-name PARITY-PC --username parityadmin --password 'P4rity!Pw' \
        --standard-username parityuser --standard-password 'U5er!Pw' \
        --output "$SH" --force >/dev/null 2>&1
strip_stamp() { grep -v 'Generated by Phoenix' "$1"; }
if diff <(strip_stamp "$REF") <(strip_stamp "$SH") >/dev/null 2>&1; then
    pass "twin output byte-identical to python e2e port (stamp normalized)"
else
    fail "twin output byte-identical to python e2e port (stamp normalized)"
fi

# T4: validation gates reject bad input, like the PS version.
expect_fail() {
    local name="$1"; shift
    if "$TWIN" "$@" >/dev/null 2>&1; then fail "$name (accepted, should reject)"; else pass "$name"; fi
}
expect_fail "rejects bad ComputerName" --computer-name 'bad name!' --username u --password p --output "$TMP/x1.xml" --force
expect_fail "rejects bad ProductKey" --computer-name TESTBOX --username u --password p --product-key nope --output "$TMP/x2.xml" --force
expect_fail "rejects duplicate account names" --computer-name TESTBOX --username u --password p --standard-username u --standard-password p2 --output "$TMP/x3.xml" --force
expect_fail "rejects missing template" --computer-name TESTBOX --username u --password p --template "$TMP/nope.xml" --output "$TMP/x4.xml" --force
# existing output without --force refuses to clobber
"$TWIN" --computer-name TESTBOX --username u --password p --output "$TMP/clobber.xml" --force >/dev/null 2>&1
if "$TWIN" --computer-name TESTBOX --username u --password p --output "$TMP/clobber.xml" >/dev/null 2>&1; then
    fail "refuses to overwrite existing output without --force"
else
    pass "refuses to overwrite existing output without --force"
fi

# T5: secrets hygiene -- password never appears in the twin's stdout/stderr.
if "$TWIN" --computer-name TESTBOX --username u --password 'Sup3rSecret!' --output "$TMP/hyg.xml" --force 2>&1 | grep -q 'Sup3rSecret!'; then
    fail "password kept out of console output"
else
    pass "password kept out of console output"
fi

echo "PASS: $PASS  FAIL: $FAIL"
(( FAIL == 0 ))
