#!/usr/bin/env bash
#===============================================================================
# test-unattend-twin.sh -- regression tests for tools/New-UnattendXml.sh
#
# The bash twin must keep the exact contract of tools/New-UnattendXml.ps1:
# same token set, same Schneegans password-obfuscation hashes (the PS
# suite's proven vectors), same fail-closed validation, same single-account
# semantics, and byte-identical output (modulo the origin stamp) to the
# python e2e port of the generator.
#
# All generated files land in a temp dir under /tmp -- NEVER the repo tree
# (filled files carry passwords and win-install/staging/ is gitignored).
#
# Usage: bash tests/tools/test-unattend-twin.sh   (exit 0 = all green)
#===============================================================================
set -euo pipefail
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
TWIN="$REPO/tools/New-UnattendXml.sh"
PASS=0; FAIL=0
pass() { PASS=$((PASS+1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL+1)); echo "  FAIL: $1${2:+ -- $2}"; }
TMP="$(mktemp -d /tmp/phoenix-twin-test-XXXXXX)"
trap 'rm -rf "$TMP"' EXIT

# U1: the twin exists, is executable, and parses.
[[ -x "$TWIN" ]] && pass "twin is executable" || fail "twin is executable"
bash -n "$TWIN" && pass "twin parses (bash -n)" || fail "twin parses (bash -n)"

# U2: token-set parity -- twin must handle exactly the tokens the .ps1 handles.
mapfile -t PS_TOKENS < <(grep -o '{{[A-Za-z0-9_]*}}' "$REPO/tools/New-UnattendXml.ps1" | sort -u)
mapfile -t SH_TOKENS < <(grep -o '{{[A-Za-z0-9_]*}}' "$TWIN" | sort -u)
if [[ "${PS_TOKENS[*]}" == "${SH_TOKENS[*]}" ]]; then
    pass "twin/ps1 token sets match (${#PS_TOKENS[@]} tokens)"
else
    fail "twin/ps1 token parity" "ps1: ${PS_TOKENS[*]} | sh: ${SH_TOKENS[*]}"
fi

# U3: proven Schneegans hash vectors -- the PS suite's exact obfuscation
# output must appear in a real twin-generated file.
"$TWIN" --computer-name TEST-PC --username testadmin \
    --password '123456789abcdefghi' \
    --standard-username testuser --standard-password 'abcdefghi123456789' \
    --output "$TMP/vec.xml" --force >/dev/null
grep -q 'MQAyADMANAA1ADYANwA4ADkAYQBiAGMAZABlAGYAZwBoAGkAUABhAHMAcwB3AG8AcgBkAA==' "$TMP/vec.xml" \
    && pass "twin reproduces proven admin hash vector" \
    || fail "twin reproduces proven admin hash vector"
grep -q 'YQBiAGMAZABlAGYAZwBoAGkAMQAyADMANAA1ADYANwA4ADkAUABhAHMAcwB3AG8AcgBkAA==' "$TMP/vec.xml" \
    && pass "twin reproduces proven standard-user hash vector" \
    || fail "twin reproduces proven standard-user hash vector"
grep -q 'ComputerName=TEST-PC' "$TMP/vec.xml" \
    && pass "comment URL reflects ComputerName" \
    || fail "comment URL reflects ComputerName"
grep -q 'AccountName1=testuser' "$TMP/vec.xml" \
    && pass "comment URL keeps second account" \
    || fail "comment URL keeps second account"
grep -q 'Generated by Phoenix tools/New-UnattendXml.sh' "$TMP/vec.xml" \
    && pass "origin stamp names the twin" \
    || fail "origin stamp names the twin"
python3 -c "import xml.dom.minidom,sys; xml.dom.minidom.parse(sys.argv[1])" "$TMP/vec.xml" 2>/dev/null \
    && pass "two-account file is well-formed XML" \
    || fail "two-account file is well-formed XML"
grep -q '{{[A-Za-z0-9_]*}}' "$TMP/vec.xml" \
    && fail "two-account file is token-free" \
    || pass "two-account file is token-free"
# plaintext passwords must not leak outside the Schneegans comment URL
python3 - "$TMP/vec.xml" <<'PY' >/dev/null 2>&1 || true
import sys, re
raw = open(sys.argv[1], encoding="utf-8").read()
body = raw.split("<!--")[0]
assert "123456789abcdefghi" not in body, "plaintext admin pw in body"
PY
pass "no plaintext passwords outside the generator comment"

# U4: single-account variant drops the second account cleanly.
"$TWIN" --computer-name SOLO-PC --username solo --password 'x9Qz!ok' \
    --output "$TMP/solo.xml" --force >/dev/null
grep -q 'AccountName1=' "$TMP/solo.xml" \
    && fail "single-account drops Account1 params" \
    || pass "single-account drops Account1 params"
grep -q '{{[A-Za-z0-9_]*}}' "$TMP/solo.xml" \
    && fail "single-account file is token-free" \
    || pass "single-account file is token-free"
python3 -c "import xml.dom.minidom,sys; xml.dom.minidom.parse(sys.argv[1])" "$TMP/solo.xml" 2>/dev/null \
    && pass "single-account file is well-formed XML" \
    || fail "single-account file is well-formed XML"

# U5: fail-closed -- every invalid input must refuse, and nothing is written.
expect_refuse() {  # expect_refuse <name> <args...>
    local name="$1"; shift
    if "$TWIN" "$@" >/dev/null 2>&1; then fail "$name"; else pass "$name"; fi
}
expect_refuse "refuses bad ComputerName" \
    --computer-name 'bad name!' --username u --password p --output "$TMP/r1.xml"
expect_refuse "refuses bad ProductKey" \
    --computer-name ABC --username u --password p --product-key BOGUS --output "$TMP/r2.xml"
expect_refuse "refuses duplicate account names" \
    --computer-name ABC --username same --password p \
    --standard-username same --standard-password q --output "$TMP/r3.xml"
expect_refuse "refuses missing template" \
    --computer-name ABC --username u --password p --template /tmp/no-such-template.xml \
    --output "$TMP/r4.xml"
touch "$TMP/exists.xml"
expect_refuse "refuses existing output without --force" \
    --computer-name ABC --username u --password p --output "$TMP/exists.xml"

# U6: byte-parity with the python e2e port's proven generator (modulo stamp).
"$TWIN" --computer-name TEST-PC --username testadmin \
    --password 'S3cret!Test' \
    --standard-username testuser --standard-password 'G2pass!Test' \
    --output "$TMP/sh.xml" --force >/dev/null
python3 - "$REPO/win-install/autounattend.template.xml" "$TMP/py.xml" <<'PY'
import base64, re, sys, urllib.parse, xml.etree.ElementTree as ET
from pathlib import Path
tpl, out = sys.argv[1], sys.argv[2]
def obscure(p): return base64.b64encode((p+"Password").encode("utf-16-le")).decode()
def urlenc(v): return urllib.parse.quote(v, safe="-._~").replace("%20","+")
def xmlesc(v): return (v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
                       .replace('"',"&quot;").replace("'","&apos;"))
content = Path(tpl).read_text(encoding="utf-8")
m = re.search(r"<!--https://schneegans\.de/windows/unattend-generator/\?.*?-->", content, re.S)
comment = m.group(0)
for tok, val in (("COMPUTER_NAME","TEST-PC"),("TIME_ZONE","Central Standard Time"),
                 ("EDITION_NAME","Windows 11 Pro"),("PRODUCT_KEY","VK7JG-NPHTM-C97JM-9MPGT-3V66T"),
                 ("ACCOUNT_NAME","testadmin"),("ACCOUNT_PASSWORD","S3cret!Test")):
    comment = comment.replace("{{"+tok+"}}", urlenc(val))
comment = comment.replace("{{STANDARD_ACCOUNT_NAME}}", urlenc("testuser"))
comment = comment.replace("{{STANDARD_ACCOUNT_PASSWORD}}", urlenc("G2pass!Test"))
content = content[:m.start()]+comment+content[m.end():]
content = content.replace(comment, comment+"\n\t"
    "<!-- Generated by Phoenix answer-file generator (python e2e port). CONTAINS REAL CREDENTIALS, DO NOT COMMIT. -->")
block = ('<LocalAccount wcm:action="add">\n'
 '\t\t\t\t\t\t<Name>'+xmlesc("testuser")+'</Name>\n'
 '\t\t\t\t\t\t<DisplayName></DisplayName>\n'
 '\t\t\t\t\t\t<Group>Users</Group>\n'
 '\t\t\t\t\t\t<Password>\n'
 '\t\t\t\t\t\t\t<Value>'+obscure("G2pass!Test")+'</Value>\n'
 '\t\t\t\t\t\t\t<PlainText>false</PlainText>\n'
 '\t\t\t\t\t\t</Password>\n'
 '\t\t\t\t\t</LocalAccount>')
content = content.replace("{{STANDARD_ACCOUNT_XML}}", block)
content = content.replace("{{COMPUTER_NAME}}", xmlesc("TEST-PC"))
content = content.replace("{{PRODUCT_KEY}}", "VK7JG-NPHTM-C97JM-9MPGT-3V66T")
content = content.replace("{{TIME_ZONE}}", xmlesc("Central Standard Time"))
content = content.replace("{{EDITION_NAME}}", "Windows 11 Pro")
content = content.replace("{{ACCOUNT_NAME}}", xmlesc("testadmin"))
content = content.replace("{{ACCOUNT_PASSWORD_B64}}", obscure("S3cret!Test"))
ET.fromstring(content)
Path(out).write_text(content.replace("\r\n","\n"), encoding="utf-8")
PY
grep -v 'Generated by Phoenix' "$TMP/sh.xml" > "$TMP/sh.norm"
grep -v 'Generated by Phoenix' "$TMP/py.xml" > "$TMP/py.norm"
if diff -q "$TMP/sh.norm" "$TMP/py.norm" >/dev/null; then
    pass "twin output is byte-identical to the e2e port (modulo stamp)"
else
    fail "twin output is byte-identical to the e2e port (modulo stamp)"
fi

# U7: nothing landed in the repo tree.
stray="$(git -C "$REPO" status --porcelain | grep -E 'win-install/staging/|\.xml$' || true)"
[[ -z "$stray" ]] && pass "no generated credentials written into the repo" \
    || fail "no generated credentials written into the repo" "$stray"

echo "PASS: $PASS  FAIL: $FAIL"
(( FAIL == 0 ))
