#!/usr/bin/env bash
#===============================================================================
# test-ps1-py-parity.sh -- Generate-Unattend.ps1 <-> generate_unattend.py parity
#
# The two generators share one options schema and one substitution algorithm.
# When PowerShell is available (Windows CI / a dev machine), this runs both
# with a fixed --generated-at stamp and diffs the outputs: they must be
# byte-identical. On machines without PowerShell (this Linux VM), it runs the
# static parity checks instead: template token-set coverage in both scripts,
# identical canonical defaults, and identical stamp/obfuscation constants.
#
# Usage: bash tests/unattend/test-ps1-py-parity.sh   (exit 0 = all green)
#===============================================================================
set -euo pipefail
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
PS1="$REPO/scripts/Generate-Unattend.ps1"
PY="$REPO/scripts/generate_unattend.py"
TPL="$REPO/win-install/autounattend.template.xml"
PASS=0; FAIL=0
pass() { PASS=$((PASS+1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL+1)); echo "  FAIL: $1${2:+ -- $2}"; }

STAMP="2026-09-10T14:00:00Z"
PW="Par1ty!Test"

if command -v pwsh >/dev/null 2>&1; then
    PWSH=pwsh
elif command -v powershell >/dev/null 2>&1; then
    PWSH=powershell
else
    PWSH=""
fi

if [[ -n "$PWSH" ]]; then
    echo "== dynamic parity (PowerShell available) =="
    OUT_PS1="$(mktemp)"; OUT_PY="$(mktemp)"
    trap 'rm -f "$OUT_PS1" "$OUT_PY"' EXIT
    # NOTE: SecureString construction here is test-only; the password is a
    # throwaway and the output goes to /tmp, never the repo.
    "$PWSH" -NoProfile -NonInteractive -Command "& '$PS1' -ComputerName PARITY-PC -Username parityadmin -Password (ConvertTo-SecureString -String '$PW' -AsPlainText -Force) -StandardUsername parityuser -StandardPassword (ConvertTo-SecureString -String 'Std$PW' -AsPlainText -Force) -GeneratedAt '$STAMP' -OutputPath '$OUT_PS1' -Force" >/dev/null
    python3 "$PY" --computer-name PARITY-PC --username parityadmin --password "$PW" \
        --standard-username parityuser --standard-password "Std$PW" \
        --generated-at "$STAMP" --output "$OUT_PY" --force >/dev/null
    if cmp -s "$OUT_PS1" "$OUT_PY"; then
        pass "PS1 and py emit byte-identical XML for the same options"
    else
        fail "PS1 and py emit byte-identical XML for the same options" \
             "$(diff "$OUT_PS1" "$OUT_PY" | head -10 | tr '\n' '|')"
    fi
else
    echo "== static parity (no PowerShell on this machine; dynamic diff runs on Windows CI) =="
    echo "  SKIP: dynamic byte-diff (pwsh not installed)"
fi

# --- static checks: run in both modes -----------------------------------------
# 1. every {{TOKEN}} in the template is handled by BOTH scripts.
#    Tokens may appear as the literal {{TOKEN}} or as a bare name in the
#    token-pair lists (the comment rewrite builds '{{' + name + '}}' at
#    runtime), so check for the name as a quoted string.
mapfile -t TOKENS < <(grep -o '{{[A-Za-z0-9_]*}}' "$TPL" | sed 's/[{}]//g' | sort -u)
missing_py=(); missing_ps1=()
for t in "${TOKENS[@]}"; do
    grep -qF "$t" "$PY"  || missing_py+=("$t")
    grep -qF "$t" "$PS1" || missing_ps1+=("$t")
done
if [[ ${#missing_py[@]} -eq 0 ]]; then
    pass "py handles all ${#TOKENS[@]} template tokens"
else
    fail "py handles all template tokens" "missing: ${missing_py[*]}"
fi
if [[ ${#missing_ps1[@]} -eq 0 ]]; then
    pass "PS1 handles all ${#TOKENS[@]} template tokens"
else
    fail "PS1 handles all template tokens" "missing: ${missing_ps1[*]}"
fi

# 2. canonical defaults agree between the two scripts
check_default() { # $1 = label, $2 = py pattern, $3 = ps1 pattern
    if grep -qF "$2" "$PY" && grep -qF "$3" "$PS1"; then
        pass "default agrees: $1"
    else
        fail "default agrees: $1"
    fi
}
check_default "timezone"        "Central Standard Time"      "Central Standard Time"
check_default "edition"         "Windows 11 Pro"             "Windows 11 Pro"
check_default "product key"     "VK7JG-NPHTM-C97JM-9MPGT-3V66T" "VK7JG-NPHTM-C97JM-9MPGT-3V66T"
check_default "input locale"    "0409:00000409"              "0409:00000409"
check_default "telemetry off"   "'off'"                      "'Off'"

# 3. parity-critical constants are byte-identical in both
if grep -qF "Generated by Phoenix answer-file generator on" "$PY" && \
   grep -qF "Generated by Phoenix answer-file generator on" "$PS1"; then
    pass "stamp text identical in both generators"
else
    fail "stamp text identical in both generators"
fi
if grep -qF '+ "Password"' "$PY" || grep -qF "password + \"Password\"" "$PY"; then
    : # py form checked below via python itself
fi
python3 - "$PY" <<'EOF'
import re, sys
src = open(sys.argv[1]).read()
sys.exit(0 if re.search(r'\(\s*password\s*\+\s*"Password"\s*\)', src) else 1)
EOF
py_obscure=$?
if [[ $py_obscure -eq 0 ]] && grep -qF "\$PlainText + 'Password'" "$PS1"; then
    pass "obfuscation suffix ('Password') identical in both"
else
    fail "obfuscation suffix ('Password') identical in both"
fi

# 4. both scripts fail closed on empty passwords
if grep -q "must not be empty" "$PY" && grep -q "cannot be empty" "$PS1"; then
    pass "both generators refuse empty passwords"
else
    fail "both generators refuse empty passwords"
fi

echo "PASS: $PASS  FAIL: $FAIL"
(( FAIL == 0 ))
