<#
.SYNOPSIS
    GUI Library - Helper functions for the script launcher GUI
    
.DESCRIPTION
    Provides functions to auto-discover scripts, extract metadata,
    and build the script catalog dynamically from the file structure.
#>

<#
.FUNCTION
    Get-ScriptMetadata
    
.DESCRIPTION
    Extracts metadata from a PowerShell script file by reading its content
    and parsing comments, requirements, and parameters.
#>
function Get-ScriptMetadata {
    param(
        [string]$ScriptPath
    )
    
    try {
        $content = Get-Content $ScriptPath -ErrorAction SilentlyContinue | Out-String
        
        $metadata = @{
            requiresAdmin = $content -match "#Requires\s+-RunAsAdministrator"
            hasParameters = $content -match "param\s*\(|`$args\[" 
            description = ""
        }
        
        # Extract description from comments
        $lines = Get-Content $ScriptPath -TotalCount 30
        foreach ($line in $lines) {
            if ($line -match "^\s*#\s*(.+)$" -and $line -notmatch "#Requires") {
                $metadata.description = $matches[1].Trim()
                break
            }
        }
        
        return $metadata
    }
    catch {
        return @{
            requiresAdmin = $false
            hasParameters = $false
            description = "Error reading script"
        }
    }
}

<#
.FUNCTION
    Build-ScriptCatalog
    
.DESCRIPTION
    Automatically scans the scripts folder and builds a complete
    script catalog organized by category.
#>
function Build-ScriptCatalog {
    param(
        [string]$ScriptsRoot
    )
    
    $catalog = @{
        version = "2.0"
        autoGenerated = $true
        lastScanned = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
        categories = @{}
        scripts = @()
    }
    
    # Find all PS1 files recursively
    $scripts = Get-ChildItem -Path $ScriptsRoot -Filter "*.ps1" -Recurse | 
               Where-Object { $_.FullName -notmatch "\\gui-launcher\.ps1$" } |
               Sort-Object FullName
    
    foreach ($script in $scripts) {
        # Calculate relative path
        $relativePath = $script.FullName.Substring($ScriptsRoot.Length + 1)
        $pathParts = $relativePath.Split("\")
        
        # Determine category hierarchy
        $mainCategory = $pathParts[0]
        $displayCategory = $mainCategory
        
        if ($pathParts.Count -gt 2 -and $pathParts[-2] -ne $mainCategory) {
            $displayCategory = "$mainCategory/$($pathParts[-2])"
        }
        
        # Extract script metadata
        $scriptMeta = Get-ScriptMetadata -ScriptPath $script.FullName
        
        $scriptObj = @{
            name = $script.BaseName
            path = $relativePath.Replace("\", "/")
            category = $displayCategory
            requiresAdmin = $scriptMeta.requiresAdmin
            hasParameters = $scriptMeta.hasParameters
            description = $scriptMeta.description
        }
        
        $catalog.scripts += $scriptObj
        
        # Add to categories
        if (-not $catalog.categories[$displayCategory]) {
            $catalog.categories[$displayCategory] = @()
        }
        
        $catalog.categories[$displayCategory] += @{
            name = $script.BaseName
            path = $relativePath.Replace("\", "/")
            requiresAdmin = $scriptMeta.requiresAdmin
            hasParameters = $scriptMeta.hasParameters
            description = $scriptMeta.description
        }
    }
    
    return $catalog
}

<#
.FUNCTION
    ConvertTo-TreeViewNodes
    
.DESCRIPTION
    Converts the script catalog into TreeView nodes for the GUI.
#>
function ConvertTo-TreeViewNodes {
    param(
        [object]$Catalog
    )
    
    $nodes = @()
    
    if ($Catalog.categories) {
        foreach ($category in ($Catalog.categories | Get-Member -MemberType NoteProperty | Sort-Object Name)) {
            $catName = $category.Name
            $catNode = New-Object System.Windows.Forms.TreeNode
            $catNode.Text = $catName
            $catNode.Tag = @{ type = "category" }
            
            $scripts = $Catalog.categories.$catName
            
            if ($scripts -is [object[]]) {
                foreach ($script in $scripts) {
                    $scriptNode = New-Object System.Windows.Forms.TreeNode
                    $scriptNode.Text = $script.name
                    $scriptNode.Tag = @{ 
                        type = "script"
                        name = $script.name
                        path = $script.path
                        requiresAdmin = $script.requiresAdmin
                        hasParameters = $script.hasParameters
                        description = $script.description
                    }
                    $catNode.Nodes.Add($scriptNode) | Out-Null
                }
            }
            else {
                $scriptNode = New-Object System.Windows.Forms.TreeNode
                $scriptNode.Text = $scripts.name
                $scriptNode.Tag = @{ 
                    type = "script"
                    name = $scripts.name
                    path = $scripts.path
                    requiresAdmin = $scripts.requiresAdmin
                    hasParameters = $scripts.hasParameters
                    description = $scripts.description
                }
                $catNode.Nodes.Add($scriptNode) | Out-Null
            }
            
            $nodes += $catNode
        }
    }
    
    return $nodes
}

<#
.FUNCTION
    Filter-CatalogBySearch
    
.DESCRIPTION
    Filters the script catalog by search query.
#>
function Filter-CatalogBySearch {
    param(
        [object]$Catalog,
        [string]$Query
    )
    
    $filtered = @{
        version = $Catalog.version
        autoGenerated = $Catalog.autoGenerated
        lastScanned = $Catalog.lastScanned
        categories = @{}
        scripts = @()
    }
    
    $query = $Query.ToLower()
    
    foreach ($category in ($Catalog.categories | Get-Member -MemberType NoteProperty)) {
        $catName = $category.Name
        $scripts = $Catalog.categories.$catName
        
        if ($scripts -is [object[]]) {
            $matching = $scripts | Where-Object { 
                $_.name.ToLower().Contains($query) -or 
                $catName.ToLower().Contains($query) -or
                $_.description.ToLower().Contains($query)
            }
        }
        else {
            if ($scripts.name.ToLower().Contains($query) -or 
                $catName.ToLower().Contains($query) -or
                $scripts.description.ToLower().Contains($query)) {
                $matching = @($scripts)
            }
            else {
                $matching = @()
            }
        }
        
        if ($matching.Count -gt 0) {
            $filtered.categories[$catName] = $matching
            $filtered.scripts += $matching
        }
    }
    
    return $filtered
}


