#!/usr/bin/env python3
"""generate_unattend.py -- stdlib-only Phoenix answer-file generator.

Fills win-install/autounattend.template.xml (the tokenized, credential-free
Schneegans-style template) with machine identity, locale, local accounts,
timezone, edition and product key, and writes the filled autounattend.xml.

This is the cross-platform twin of scripts/Generate-Unattend.ps1: the same
options schema, the same substitution algorithm, byte-identical output for
the same inputs (see tests/unattend/test-ps1-py-parity.sh). The future
Svelte+Tauri config GUI calls this headlessly with --options-json.

Credentials rule: the template carries zero credentials; the filled file
carries real local-account passwords (the unattend format requires them --
even the "obscured" form is reversible) and is written to
win-install/staging/, which is gitignored. NEVER commit a filled file.

Usage:
    python3 scripts/generate_unattend.py --computer-name NIGHTMARE \\
        --username brando --timezone "Central Standard Time"
    # --password prompts via getpass when omitted (never in shell history)

    python3 scripts/generate_unattend.py --options-json config/machine.json --force
"""

import argparse
import base64
import getpass
import json
import re
import sys
import urllib.parse
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TEMPLATE = REPO / "win-install" / "autounattend.template.xml"
DEFAULT_OUT = REPO / "win-install" / "staging" / "autounattend.xml"

GENERIC_PRO_KEY = "VK7JG-NPHTM-C97JM-9MPGT-3V66T"  # MS public generic Win11 Pro key (not a license)

# The stamp text must stay byte-identical with scripts/Generate-Unattend.ps1
# (it is part of the PS1<->py parity contract).
STAMP = ("<!-- Generated by Phoenix answer-file generator on {when}. "
         "CONTAINS REAL CREDENTIALS, DO NOT COMMIT. -->")

# Raw-text anchor inside the template's embedded Specialize.ps1 <File> block
# (the proven Schneegans file; single backslashes in the registry paths).
_BYPASS_NRO = ('\t{\n\t\treg.exe add "HKLM\\SOFTWARE\\Microsoft'
               '\\Windows\\CurrentVersion\\OOBE" /v BypassNRO'
               ' /t REG_DWORD /d 1 /f;\n\t};')

_TELEMETRY_BLOCK = (
    '\n'
    '\t{\n\t\treg.exe add "HKLM\\SOFTWARE\\Policies\\Microsoft'
    '\\Windows\\DataCollection" /v AllowTelemetry /t REG_DWORD /d 0 /f;\n\t};\n'
    '\t{\n\t\treg.exe add "HKLM\\SOFTWARE\\Microsoft'
    '\\Windows\\CurrentVersion\\Policies\\DataCollection"'
    ' /v AllowTelemetry /t REG_DWORD /d 0 /f;\n\t};'
)

# Hardcoded locale values in the template (fail closed if they ever change).
_TEMPLATE_LOCALE = {
    "input_locale": "0409:00000409",
    "system_locale": "en-001",
    "ui_language": "en-US",
    "user_locale": "en-001",
}


def obscure(password):
    """Schneegans 'ObscurePasswords' encoding: base64(UTF-16LE(password + 'Password'))."""
    return base64.b64encode((password + "Password").encode("utf-16-le")).decode("ascii")


def urlenc(value):
    """Match [Uri]::EscapeDataString with spaces as '+', like the proven file."""
    return urllib.parse.quote(value, safe="-._~").replace("%20", "+")


def xmlesc(value):
    """Match [System.Security.SecurityElement]::Escape."""
    return (value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;").replace("'", "&apos;"))


def validate(opts):
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9\-]{0,14}", opts["computer_name"]):
        raise ValueError("computer_name must be 1-15 chars: letters, digits, hyphens")
    if not opts["username"] or re.search(r'[<>"\r\n]', opts["username"]):
        raise ValueError("username must be non-empty and contain no <>\" or newlines")
    if not opts["password"]:
        raise ValueError("password must not be empty (local admin WITH a password, never blank)")
    std = opts.get("standard_username") or ""
    if std:
        if not opts.get("standard_password"):
            raise ValueError("standard_password must not be empty when standard_username is set")
        if std == opts["username"]:
            raise ValueError("standard_username must differ from username")
        if re.search(r'[<>"\r\n]', std):
            raise ValueError("standard_username contains illegal characters")
    if not re.fullmatch(r"[A-Z0-9]{5}(-[A-Z0-9]{5}){4}", opts["product_key"], re.I):
        raise ValueError("product_key must look like XXXXX-XXXXX-XXXXX-XXXXX-XXXXX")
    if not opts["timezone"]:
        raise ValueError("timezone must not be empty")
    if re.search(r'["\r\n]', opts["edition"]):
        raise ValueError("edition must not contain quotes or newlines")
    if opts["telemetry"] not in ("off", "basic"):
        raise ValueError("telemetry must be 'off' or 'basic'")


def _rewrite_comment(comment, o):
    for tok, val in (("COMPUTER_NAME", o["computer_name"]),
                     ("TIME_ZONE", o["timezone"]),
                     ("EDITION_NAME", o["edition"]),
                     ("PRODUCT_KEY", o["product_key"]),
                     ("ACCOUNT_NAME", o["username"]),
                     ("ACCOUNT_PASSWORD", o["password"])):
        comment = comment.replace("{{" + tok + "}}", urlenc(val))
    std = o.get("standard_username") or ""
    if std:
        comment = comment.replace("{{STANDARD_ACCOUNT_NAME}}", urlenc(std))
        comment = comment.replace("{{STANDARD_ACCOUNT_PASSWORD}}",
                                  urlenc(o["standard_password"]))
    else:
        # Single-account file: drop the second-account params from the regen URL.
        comment = re.sub(r"&Account(Name|DisplayName|Password|Group)1=[^&]*", "", comment)
    # Keep the round-trippable Schneegans URL honest about locale choices.
    keyboard = o["input_locale"].split(":")[-1]
    comment = re.sub(r"([?&])UILanguage=[^&]*", r"\g<1>UILanguage=" + urlenc(o["ui_language"]), comment)
    comment = re.sub(r"([?&])Locale=[^&]*", r"\g<1>Locale=" + urlenc(o["system_locale"]), comment)
    comment = re.sub(r"([?&])Keyboard=[^&]*", r"\g<1>Keyboard=" + urlenc(keyboard), comment)
    return comment


def _standard_account_block(std_user, std_pw):
    return ('<LocalAccount wcm:action="add">\n'
            '\t\t\t\t\t\t<Name>' + xmlesc(std_user) + '</Name>\n'
            '\t\t\t\t\t\t<DisplayName></DisplayName>\n'
            '\t\t\t\t\t\t<Group>Users</Group>\n'
            '\t\t\t\t\t\t<Password>\n'
            '\t\t\t\t\t\t\t<Value>' + obscure(std_pw) + '</Value>\n'
            '\t\t\t\t\t\t\t<PlainText>false</PlainText>\n'
            '\t\t\t\t\t\t</Password>\n'
            '\t\t\t\t\t</LocalAccount>')


def generate(opts, out_path):
    """Fill the template with opts; write the filled file to out_path."""
    validate(opts)
    if not TEMPLATE.is_file():
        raise FileNotFoundError("template not found: %s" % TEMPLATE)
    content = TEMPLATE.read_text(encoding="utf-8")

    # --- rewrite the Schneegans generator comment (comment-only tokens) ---
    m = re.search(r"<!--https://schneegans\.de/windows/unattend-generator/\?.*?-->",
                  content, re.S)
    if not m:
        raise ValueError("template is missing the Schneegans generator comment; refusing to guess")
    comment = _rewrite_comment(m.group(0), opts)
    content = content[:m.start()] + comment + content[m.end():]

    # Stamp the file so its origin is obvious on the USB (no '--' inside an
    # XML comment -- a '--' mid-comment breaks well-formedness).
    when = opts.get("generated_at") or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = content.replace(comment, comment + "\n\t" + STAMP.format(when=when))

    # --- telemetry minimization: reg blocks appended to Specialize.ps1 ---
    if opts["telemetry"] == "off":
        i = content.find(_BYPASS_NRO)
        if i < 0:
            raise ValueError("telemetry anchor (BypassNRO block) not found in template; refusing to guess")
        content = content[:i + len(_BYPASS_NRO)] + _TELEMETRY_BLOCK + content[i + len(_BYPASS_NRO):]

    # --- locale / keyboard (fail closed if the template's hardcoded values change) ---
    for key, new_val in (("input_locale", opts["input_locale"]),
                         ("system_locale", opts["system_locale"]),
                         ("ui_language", opts["ui_language"]),
                         ("user_locale", opts["user_locale"])):
        old = _TEMPLATE_LOCALE[key]
        tag = {"input_locale": "InputLocale", "system_locale": "SystemLocale",
               "ui_language": "UILanguage", "user_locale": "UserLocale"}[key]
        needle = "<%s>%s</%s>" % (tag, old, tag)
        if needle not in content:
            raise ValueError("locale anchor %r not found in template; refusing to guess" % needle)
        content = content.replace(needle, "<%s>%s</%s>" % (tag, xmlesc(new_val), tag))

    # --- fill body tokens ---
    std = opts.get("standard_username") or ""
    if std:
        content = content.replace("{{STANDARD_ACCOUNT_XML}}",
                                  _standard_account_block(std, opts["standard_password"]))
    else:
        content = re.sub(r"(?m)^\t*{{STANDARD_ACCOUNT_XML}}\r?\n", "", content)

    content = content.replace("{{COMPUTER_NAME}}", xmlesc(opts["computer_name"]))
    content = content.replace("{{PRODUCT_KEY}}", opts["product_key"])
    content = content.replace("{{TIME_ZONE}}", xmlesc(opts["timezone"]))
    content = content.replace("{{EDITION_NAME}}", opts["edition"])
    content = content.replace("{{ACCOUNT_NAME}}", xmlesc(opts["username"]))
    content = content.replace("{{ACCOUNT_PASSWORD_B64}}", obscure(opts["password"]))

    # --- safety: no token may survive ---
    leftover = re.search(r"\{\{[A-Z_]+\}\}", content)
    if leftover:
        raise ValueError("unfilled token left in output: %s. Aborting." % leftover.group(0))

    # --- the filled file must still be well-formed XML ---
    try:
        ET.fromstring(content)
    except ET.ParseError as e:
        raise ValueError("generated file is not well-formed XML: %s" % e)

    # --- write to staging (match the template: UTF-8 no BOM, LF) ---
    out_path = Path(out_path)
    if out_path.exists() and not opts.get("force"):
        raise FileExistsError("output exists: %s (use --force to overwrite)" % out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content.replace("\r\n", "\n"), encoding="utf-8", newline="\n")
    return out_path


DEFAULTS = {
    "computer_name": None,      # required
    "username": None,           # required
    "password": None,           # prompted via getpass when omitted on a TTY
    "standard_username": "",
    "standard_password": None,  # prompted when standard_username is set
    "timezone": "Central Standard Time",
    "edition": "Windows 11 Pro",
    "product_key": GENERIC_PRO_KEY,
    "input_locale": "0409:00000409",
    "system_locale": "en-001",
    "ui_language": "en-US",
    "user_locale": "en-001",
    "telemetry": "off",
    "generated_at": None,
    "force": False,
}


def load_options(args):
    """Merge precedence: built-in defaults < --options-json < CLI flags."""
    opts = dict(DEFAULTS)
    if args.options_json:
        file_opts = json.loads(Path(args.options_json).read_text(encoding="utf-8"))
        unknown = set(file_opts) - set(opts)
        if unknown:
            raise ValueError("unknown option(s) in %s: %s"
                             % (args.options_json, ", ".join(sorted(unknown))))
        opts.update({k: v for k, v in file_opts.items()})
    cli = {k: v for k, v in vars(args).items()
           if k in opts and v is not None and k != "options_json"}
    # store_true --force defaults False; only True overrides.
    if not cli.get("force"):
        cli.pop("force", None)
    opts.update(cli)
    if not opts["computer_name"]:
        raise ValueError("--computer-name is required")
    if not opts["username"]:
        raise ValueError("--username is required")
    if not opts["password"]:
        if not sys.stdin.isatty():
            raise ValueError("--password is required when stdin is not a TTY (headless mode)")
        opts["password"] = getpass.getpass("Password for local admin '%s': " % opts["username"])
    std = opts.get("standard_username")
    if std and not opts.get("standard_password"):
        if not sys.stdin.isatty():
            raise ValueError("--standard-password is required when stdin is not a TTY")
        opts["standard_password"] = getpass.getpass(
            "Password for standard account '%s': " % std)
    return opts


def main(argv=None):
    p = argparse.ArgumentParser(description="Generate a Phoenix autounattend.xml answer file.")
    # All defaults are None here so --options-json values survive; CLI wins.
    # (computer-name/username are validated as required after the merge.)
    p.add_argument("--computer-name", default=None, help="NetBIOS name, 1-15 chars [A-Za-z0-9-]")
    p.add_argument("--username", default=None, help="Primary local account (Administrators + AutoLogon x1)")
    p.add_argument("--password", default=None, help="Admin password; prompts via getpass when omitted")
    p.add_argument("--standard-username", default=None, help="Optional second account (Users group)")
    p.add_argument("--standard-password", default=None, help="Standard account password; prompts when omitted")
    p.add_argument("--timezone", default=None, help="Windows timezone ID")
    p.add_argument("--edition", default=None,
                   help="Image /Name passed to dism; must match install.wim/esd")
    p.add_argument("--product-key", default=None, help="Setup product key")
    p.add_argument("--input-locale", default=None, help="Keyboard layout ID")
    p.add_argument("--system-locale", default=None)
    p.add_argument("--ui-language", default=None)
    p.add_argument("--user-locale", default=None)
    p.add_argument("--telemetry", default=None, choices=("off", "basic"),
                   help="'off' injects AllowTelemetry=0 reg blocks into Specialize.ps1")
    p.add_argument("--generated-at", default=None,
                   help="Stamp override (UTC ISO); fixes output for PS1<->py parity tests")
    p.add_argument("--options-json", default=None,
                   help="JSON options file (the Tauri GUI path); CLI flags override it")
    p.add_argument("--output", default=str(DEFAULT_OUT),
                   help="Output path (default: win-install/staging/, gitignored)")
    p.add_argument("--force", action="store_true", help="Overwrite an existing output file")
    args = p.parse_args(argv)

    try:
        opts = load_options(args)
        out = generate(opts, args.output)
    except (ValueError, FileExistsError, FileNotFoundError) as e:
        print("error: %s" % e, file=sys.stderr)
        return 1

    print("Wrote %s" % out)
    print("  Computer : %s" % opts["computer_name"])
    print("  Admin    : %s (Administrators, AutoLogon x1)" % opts["username"])
    if opts.get("standard_username"):
        print("  Standard : %s (Users)" % opts["standard_username"])
    print("  Timezone : %s" % opts["timezone"])
    print("  Edition  : %s" % opts["edition"])
    print("  Telemetry: %s" % opts["telemetry"])
    print()
    print("Staging dir is gitignored - copy this file to the USB as autounattend.xml.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
