<#
.SYNOPSIS
    Emits a self-contained, setup-time PowerShell installer for the Phoenix app picker.

.DESCRIPTION
    Reads the curated catalog in data/choco-install/apps.json (or an explicit package
    list) and generates a PowerShell script suitable for the oobeSystem
    FirstLogonCommands pass of autounattend.xml.

    The emitted script:
      - installs Chocolatey itself when missing (online bootstrap),
      - refreshes PATH so `choco` is usable in the same process,
      - installs the selected packages with `choco install -y --no-progress`,
      - skips packages already installed (idempotent; safe to re-run),
      - logs everything to C:\Phoenix\Logs\app-install.log,
      - never fails OOBE: it always exits 0 even when packages fail.

    Packages flagged `"source": "manual"` in apps.json (not on Chocolatey)
    are skipped with a warning printed at generation time.

.EXAMPLE
    .\New-AppInstallScript.ps1 -UseDefaults -OutFile ..\..\win-install\app-install.ps1

.EXAMPLE
    .\New-AppInstallScript.ps1 -Packages GoogleChrome, Steam, VLC
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    # Explicit package names to install. Mutually exclusive with -UseDefaults.
    [string[]]$Packages,

    # Use the defaultSelected entries from apps.json (excluding manual-install entries).
    [switch]$UseDefaults,

    # Path to the picker catalog. Defaults to data/choco-install/apps.json relative to the repo root.
    [string]$AppsJson,

    # Optional Chocolatey source override baked into the emitted script
    # (e.g. a local/internalized feed for air-gap installs).
    [string]$ChocoSource = 'https://community.chocolatey.org/api/v2/',

    # Where to write the emitted script. Prints to stdout when omitted.
    [string]$OutFile
)

$ErrorActionPreference = 'Stop'

if (-not $AppsJson) {
    $repoRoot = (Get-Item (Join-Path $PSScriptRoot '..')).FullName
    $AppsJson = Join-Path $repoRoot 'data\choco-install\apps.json'
}

if ($Packages -and $UseDefaults) {
    throw 'Use either -Packages or -UseDefaults, not both.'
}

$selected = @()
if ($Packages) {
    $selected = @($Packages)
}
else {
    if (-not (Test-Path $AppsJson)) { throw "Catalog not found: $AppsJson" }
    $catalog = Get-Content -Raw -Path $AppsJson | ConvertFrom-Json
    foreach ($entry in $catalog) {
        if (-not $entry.defaultSelected) { continue }
        if ($entry.source -eq 'manual') {
            Write-Warning "Skipping '$($entry.package)': $($entry.note)"
            continue
        }
        $selected += $entry.package
    }
}

if ($selected.Count -eq 0) { throw 'No packages selected; nothing to emit.' }

foreach ($name in $selected) {
    if ($name -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]*$') {
        throw "Suspicious package name rejected: '$name'"
    }
}

# Escape for single-quoted PowerShell literals in the emitted script.
$packageLines = $selected | ForEach-Object { "    '$($_.Replace("'", "''"))'," }
$packageBlock = ($packageLines -join "`r`n").TrimEnd(',')

$script = @'
<#
    Phoenix app install — generated by tools\New-AppInstallScript.ps1.
    Intended for oobeSystem FirstLogonCommands in autounattend.xml, e.g.:

      <FirstLogonCommands>
        <SynchronousCommand wcm:action="add">
          <Order>1</Order>
          <CommandLine>powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Windows\Setup\Scripts\app-install.ps1"</CommandLine>
          <Description>Phoenix app install</Description>
        </SynchronousCommand>
      </FirstLogonCommands>

    Idempotent and logged; always exits 0 so OOBE is never blocked.
#>
[CmdletBinding()]
param(
    # Override the Chocolatey source (air-gap: point at an internalized local feed).
    [string]$Source = '@@CHOCO_SOURCE@@'
)

$ErrorActionPreference = 'Continue'
$LogDir  = "$env:SystemDrive\Phoenix\Logs"
$LogFile = Join-Path $LogDir 'app-install.log'

function Write-PhoenixLog {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [string]$Level = 'INFO'
    )
    $line = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')][$Level] $Message"
    try {
        if (-not (Test-Path $LogDir)) {
            New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
        }
        Add-Content -Path $LogFile -Value $line -Encoding UTF8
    } catch {
        # Logging must never break the install.
    }
    Write-Output $line
}

function Update-SessionPath {
    # The Chocolatey bootstrap changes the machine PATH; pick it up without a reboot.
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') +
                ';' + [System.Environment]::GetEnvironmentVariable('Path', 'User')
}

function Test-ChocoInstalled {
    return [bool](Get-Command 'choco' -ErrorAction SilentlyContinue)
}

function Install-Chocolatey {
    if (Test-ChocoInstalled) {
        Write-PhoenixLog 'Chocolatey already present; skipping bootstrap.'
        return $true
    }
    Write-PhoenixLog 'Bootstrapping Chocolatey (online installer)...'
    try {
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol =
            [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString(
            'https://community.chocolatey.org/install.ps1'))
        Update-SessionPath
    } catch {
        Write-PhoenixLog "Chocolatey bootstrap failed: $($_.Exception.Message)" 'ERROR'
        return $false
    }
    if (-not (Test-ChocoInstalled)) {
        Write-PhoenixLog 'Bootstrap reported success but choco is not on PATH.' 'ERROR'
        return $false
    }
    Write-PhoenixLog 'Chocolatey installed.'
    return $true
}

function Test-PackageInstalled {
    param([Parameter(Mandatory = $true)][string]$Name)
    $hit = & choco list --local-only --exact --limit-output $Name 2>$null |
        Where-Object { ($_ -split '\|')[0].Trim().ToLower() -eq $Name.ToLower() }
    return [bool]$hit
}

function Install-PhoenixPackage {
    param([Parameter(Mandatory = $true)][string]$Name)
    if (Test-PackageInstalled $Name) {
        Write-PhoenixLog "$Name already installed; skipping."
        return $true
    }
    Write-PhoenixLog "Installing $Name ..."
    $installOutput = & choco install $Name -y --no-progress --limit-output --source="$Source" 2>&1
    foreach ($outLine in $installOutput) { Write-PhoenixLog $outLine }
    if ($LASTEXITCODE -eq 0 -or (Test-PackageInstalled $Name)) {
        Write-PhoenixLog "$Name installed."
        return $true
    }
    Write-PhoenixLog "$Name failed (exit $LASTEXITCODE)." 'ERROR'
    return $false
}

Write-PhoenixLog '--- Phoenix app install started ---'

if (-not (Install-Chocolatey)) {
    Write-PhoenixLog 'Aborting: Chocolatey is unavailable.' 'ERROR'
    exit 0
}

$Packages = @(
@@PACKAGE_BLOCK@@
)

$failed = @()
foreach ($pkg in $Packages) {
    if (-not (Install-PhoenixPackage $pkg)) { $failed += $pkg }
}

if ($failed.Count -gt 0) {
    Write-PhoenixLog ("Failed packages: " + ($failed -join ', ')) 'ERROR'
} else {
    Write-PhoenixLog 'All selected packages installed.'
}

Write-PhoenixLog '--- Phoenix app install finished ---'
exit 0
'@

$script = $script.Replace('@@PACKAGE_BLOCK@@', $packageBlock)
$script = $script.Replace('@@CHOCO_SOURCE@@', $ChocoSource.Replace("'", "''"))
$script = $script.TrimStart() + "`r`n"

if ($OutFile) {
    if ($PSCmdlet.ShouldProcess($OutFile, 'Write emitted installer script')) {
        Set-Content -Path $OutFile -Value $script -Encoding UTF8
        Write-Output "Wrote $($selected.Count) packages to $OutFile"
    }
}
else {
    Write-Output $script
}
